kind: Service
apiVersion: v1
metadata:
  name: order-service
spec:
  selector:
    run: order-service
  ports:
    - name: port1
      protocol: TCP
      port: 3333
      targetPort: 3333
  type: NodePort
